include:
  - path: "compose/dashboard/docker-compose.yml"
  - path: "compose/mc/docker-compose.yml"
  - path: "compose/mc-modded/docker-compose.yml"
  - path: "compose/media/docker-compose.yml"
  - path: "compose/network/docker-compose.yml"
  - path: "compose/terraria/docker-compose.yml"
  - path: "compose/watchtower/docker-compose.yml"
  - path: "compose/immich/docker-compose.yml"
  - path: "compose/ark/docker-compose.yml"
  - path: "compose/hdd_monitoring/docker-compose.yml"
  - path: "compose/firefox/docker-compose.yml"
  - path: "compose/p2p/docker-compose.yml"