services:
  watchtower:
    container_name: watchtower
    image: nickfedor/watchtower:latest
    environment:
      - TZ=$TZ
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_UPDATE_ON_START=true
      - WATCHTOWER_POLL_INTERVAL=43200 # half of 1 day
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock